/*
SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// DNSLoadBalancerListerExpansion allows custom methods to be added to
// DNSLoadBalancerLister.
type DNSLoadBalancerListerExpansion interface{}

// DNSLoadBalancerNamespaceListerExpansion allows custom methods to be added to
// DNSLoadBalancerNamespaceLister.
type DNSLoadBalancerNamespaceListerExpansion interface{}

// DNSLoadBalancerEndpointListerExpansion allows custom methods to be added to
// DNSLoadBalancerEndpointLister.
type DNSLoadBalancerEndpointListerExpansion interface{}

// DNSLoadBalancerEndpointNamespaceListerExpansion allows custom methods to be added to
// DNSLoadBalancerEndpointNamespaceLister.
type DNSLoadBalancerEndpointNamespaceListerExpansion interface{}
