/*
SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/gardener/dnslb-controller-manager/pkg/apis/loadbalancer/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNSLoadBalancerEndpoints implements DNSLoadBalancerEndpointInterface
type FakeDNSLoadBalancerEndpoints struct {
	Fake *FakeLoadbalancerV1beta1
	ns   string
}

var dnsloadbalancerendpointsResource = schema.GroupVersionResource{Group: "loadbalancer.gardener.cloud", Version: "v1beta1", Resource: "dnsloadbalancerendpoints"}

var dnsloadbalancerendpointsKind = schema.GroupVersionKind{Group: "loadbalancer.gardener.cloud", Version: "v1beta1", Kind: "DNSLoadBalancerEndpoint"}

// Get takes name of the dNSLoadBalancerEndpoint, and returns the corresponding dNSLoadBalancerEndpoint object, and an error if there is any.
func (c *FakeDNSLoadBalancerEndpoints) Get(name string, options v1.GetOptions) (result *v1beta1.DNSLoadBalancerEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dnsloadbalancerendpointsResource, c.ns, name), &v1beta1.DNSLoadBalancerEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.DNSLoadBalancerEndpoint), err
}

// List takes label and field selectors, and returns the list of DNSLoadBalancerEndpoints that match those selectors.
func (c *FakeDNSLoadBalancerEndpoints) List(opts v1.ListOptions) (result *v1beta1.DNSLoadBalancerEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dnsloadbalancerendpointsResource, dnsloadbalancerendpointsKind, c.ns, opts), &v1beta1.DNSLoadBalancerEndpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.DNSLoadBalancerEndpointList{ListMeta: obj.(*v1beta1.DNSLoadBalancerEndpointList).ListMeta}
	for _, item := range obj.(*v1beta1.DNSLoadBalancerEndpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNSLoadBalancerEndpoints.
func (c *FakeDNSLoadBalancerEndpoints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dnsloadbalancerendpointsResource, c.ns, opts))

}

// Create takes the representation of a dNSLoadBalancerEndpoint and creates it.  Returns the server's representation of the dNSLoadBalancerEndpoint, and an error, if there is any.
func (c *FakeDNSLoadBalancerEndpoints) Create(dNSLoadBalancerEndpoint *v1beta1.DNSLoadBalancerEndpoint) (result *v1beta1.DNSLoadBalancerEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dnsloadbalancerendpointsResource, c.ns, dNSLoadBalancerEndpoint), &v1beta1.DNSLoadBalancerEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.DNSLoadBalancerEndpoint), err
}

// Update takes the representation of a dNSLoadBalancerEndpoint and updates it. Returns the server's representation of the dNSLoadBalancerEndpoint, and an error, if there is any.
func (c *FakeDNSLoadBalancerEndpoints) Update(dNSLoadBalancerEndpoint *v1beta1.DNSLoadBalancerEndpoint) (result *v1beta1.DNSLoadBalancerEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dnsloadbalancerendpointsResource, c.ns, dNSLoadBalancerEndpoint), &v1beta1.DNSLoadBalancerEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.DNSLoadBalancerEndpoint), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDNSLoadBalancerEndpoints) UpdateStatus(dNSLoadBalancerEndpoint *v1beta1.DNSLoadBalancerEndpoint) (*v1beta1.DNSLoadBalancerEndpoint, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dnsloadbalancerendpointsResource, "status", c.ns, dNSLoadBalancerEndpoint), &v1beta1.DNSLoadBalancerEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.DNSLoadBalancerEndpoint), err
}

// Delete takes name of the dNSLoadBalancerEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeDNSLoadBalancerEndpoints) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dnsloadbalancerendpointsResource, c.ns, name), &v1beta1.DNSLoadBalancerEndpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNSLoadBalancerEndpoints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dnsloadbalancerendpointsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.DNSLoadBalancerEndpointList{})
	return err
}

// Patch applies the patch and returns the patched dNSLoadBalancerEndpoint.
func (c *FakeDNSLoadBalancerEndpoints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.DNSLoadBalancerEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dnsloadbalancerendpointsResource, c.ns, name, data, subresources...), &v1beta1.DNSLoadBalancerEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.DNSLoadBalancerEndpoint), err
}
