# SPDX-FileCopyrightText: 2018 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: loadbalancer.gardener.cloud/v1beta1
kind: DNSLoadBalancer
metadata:
  name: test
  namespace: garden
spec:
  DNSName: test.garden.ring01.dev.k8s.ondemand.com
  healthPath:  /healthz
  type: Balanced
  endpointValidityInterval: 5m
