# SPDX-FileCopyrightText: 2018 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: garden
  annotations:
    loadbalancer.gardener.cloud/dnsloadbalancer: test
    xxx.gardener.cloud/xxx: test
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  type: LoadBalancer
  selector:
    app: garden-kube-apiserver
  

