required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen"
]

[[constraint]]
  branch = "master"
  name = "github.com/gardener/controller-manager-library"

[[constraint]]
  branch = "master"
  name = "github.com/gardener/external-dns-management"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.1"

# https://github.com/kubernetes/kubernetes/issues/17162
# https://github.com/kubernetes-incubator/service-catalog/pull/1204

[[override]]
  name = "github.com/json-iterator/go"
  version = "^1.1.4"

[[override]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.4"

# Dependencies for testing purposes only
[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
