#!/bin/bash
#
# SPDX-FileCopyrightText: 2018 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

DIR=cmd/dnslb-controller-manager
export GARDENCONFIG=~/k8s/GARDEN/clusters/cluster-ring01-garden/kubeconfig.yaml

if [ "$1"  == -w ]; then
  shift
  watch=(--watches "$DIR/watches.yaml")
else
  watch=( )
fi

CLUSTER=a
case "$1" in 
  -a|-b|-c) 
      CLUSTER="$(expr -- "$1" : "-\(.*\)")"
      shift;;
  --kubeconfig)
      export KUBECONFIG=~/k8s/CLUSTERS/"$2"
      CLUSTER=
      shift 2;;
esac

if [ -n "$CLUSTER" ]; then
  echo cluster = $CLUSTER
  export KUBECONFIG=~/.gex/cache/ring01/projects/garden/$CLUSTER/kubeconfig.yaml
  target=(--targetkube "$GARDENCONFIG" --cluster "$CLUSTER")
else 
  target=()
fi

cmd=( "$DIR/dnslb-controller-manager" --kubeconfig "$KUBECONFIG" "${target[@]}" "${watch[@]}"  "$@" )
echo "${cmd[@]}"
"${cmd[@]}"
