#!/bin/bash
#
# Copyright 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DIR=cmd/dnslb-controller-manager
export GARDENCONFIG=~/k8s/GARDEN/clusters/cluster-ring01-garden/kubeconfig.yaml

if [ "$1"  == -w ]; then
  shift
  watch=(--watches "$DIR/watches.yaml")
else
  watch=( )
fi

CLUSTER=a
case "$1" in 
  -a|-b|-c) 
      CLUSTER="$(expr -- "$1" : "-\(.*\)")"
      shift;;
esac
echo cluster = $CLUSTER

export KUBECONFIG=~/.gex/cache/ring01/projects/garden/$CLUSTER/kubeconfig.yaml

cmd=( "$DIR/dnslb-controller-manager" --kubeconfig "$KUBECONFIG" --targetkube "$GARDENCONFIG" --cluster $CLUSTER "${watch[@]}"  "$@" )
echo "${cmd[@]}"
"${cmd[@]}"
