/*
SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/gardener/dnslb-controller-manager/pkg/apis/loadbalancer/v1beta1"
	scheme "github.com/gardener/dnslb-controller-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DNSLoadBalancerEndpointsGetter has a method to return a DNSLoadBalancerEndpointInterface.
// A group's client should implement this interface.
type DNSLoadBalancerEndpointsGetter interface {
	DNSLoadBalancerEndpoints(namespace string) DNSLoadBalancerEndpointInterface
}

// DNSLoadBalancerEndpointInterface has methods to work with DNSLoadBalancerEndpoint resources.
type DNSLoadBalancerEndpointInterface interface {
	Create(*v1beta1.DNSLoadBalancerEndpoint) (*v1beta1.DNSLoadBalancerEndpoint, error)
	Update(*v1beta1.DNSLoadBalancerEndpoint) (*v1beta1.DNSLoadBalancerEndpoint, error)
	UpdateStatus(*v1beta1.DNSLoadBalancerEndpoint) (*v1beta1.DNSLoadBalancerEndpoint, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.DNSLoadBalancerEndpoint, error)
	List(opts v1.ListOptions) (*v1beta1.DNSLoadBalancerEndpointList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.DNSLoadBalancerEndpoint, err error)
	DNSLoadBalancerEndpointExpansion
}

// dNSLoadBalancerEndpoints implements DNSLoadBalancerEndpointInterface
type dNSLoadBalancerEndpoints struct {
	client rest.Interface
	ns     string
}

// newDNSLoadBalancerEndpoints returns a DNSLoadBalancerEndpoints
func newDNSLoadBalancerEndpoints(c *LoadbalancerV1beta1Client, namespace string) *dNSLoadBalancerEndpoints {
	return &dNSLoadBalancerEndpoints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dNSLoadBalancerEndpoint, and returns the corresponding dNSLoadBalancerEndpoint object, and an error if there is any.
func (c *dNSLoadBalancerEndpoints) Get(name string, options v1.GetOptions) (result *v1beta1.DNSLoadBalancerEndpoint, err error) {
	result = &v1beta1.DNSLoadBalancerEndpoint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsloadbalancerendpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DNSLoadBalancerEndpoints that match those selectors.
func (c *dNSLoadBalancerEndpoints) List(opts v1.ListOptions) (result *v1beta1.DNSLoadBalancerEndpointList, err error) {
	result = &v1beta1.DNSLoadBalancerEndpointList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsloadbalancerendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dNSLoadBalancerEndpoints.
func (c *dNSLoadBalancerEndpoints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dnsloadbalancerendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a dNSLoadBalancerEndpoint and creates it.  Returns the server's representation of the dNSLoadBalancerEndpoint, and an error, if there is any.
func (c *dNSLoadBalancerEndpoints) Create(dNSLoadBalancerEndpoint *v1beta1.DNSLoadBalancerEndpoint) (result *v1beta1.DNSLoadBalancerEndpoint, err error) {
	result = &v1beta1.DNSLoadBalancerEndpoint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dnsloadbalancerendpoints").
		Body(dNSLoadBalancerEndpoint).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dNSLoadBalancerEndpoint and updates it. Returns the server's representation of the dNSLoadBalancerEndpoint, and an error, if there is any.
func (c *dNSLoadBalancerEndpoints) Update(dNSLoadBalancerEndpoint *v1beta1.DNSLoadBalancerEndpoint) (result *v1beta1.DNSLoadBalancerEndpoint, err error) {
	result = &v1beta1.DNSLoadBalancerEndpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dnsloadbalancerendpoints").
		Name(dNSLoadBalancerEndpoint.Name).
		Body(dNSLoadBalancerEndpoint).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *dNSLoadBalancerEndpoints) UpdateStatus(dNSLoadBalancerEndpoint *v1beta1.DNSLoadBalancerEndpoint) (result *v1beta1.DNSLoadBalancerEndpoint, err error) {
	result = &v1beta1.DNSLoadBalancerEndpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dnsloadbalancerendpoints").
		Name(dNSLoadBalancerEndpoint.Name).
		SubResource("status").
		Body(dNSLoadBalancerEndpoint).
		Do().
		Into(result)
	return
}

// Delete takes name of the dNSLoadBalancerEndpoint and deletes it. Returns an error if one occurs.
func (c *dNSLoadBalancerEndpoints) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsloadbalancerendpoints").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dNSLoadBalancerEndpoints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsloadbalancerendpoints").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dNSLoadBalancerEndpoint.
func (c *dNSLoadBalancerEndpoints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.DNSLoadBalancerEndpoint, err error) {
	result = &v1beta1.DNSLoadBalancerEndpoint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dnsloadbalancerendpoints").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
