/*
SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type DNSLoadBalancerExpansion interface{}

type DNSLoadBalancerEndpointExpansion interface{}
