# SPDX-FileCopyrightText: 2018 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

#
# service account
#
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: dnslb
  name: dnslb
  namespace: garden

---
#
# permissions
#
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: dnslb
  name: dnslb
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - update
      - watch

  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - update

  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - update
      - watch

  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update

  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get

  - apiGroups:
      - loadbalancer.gardener.cloud
    resources:
      - dnsloadbalancers
      - dnsloadbalancerendpoints
      - dnsproviders
    verbs:
      - get
      - list
      - update
      - watch

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - update
      - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: dnslb
  name: dnslb
  namespace: garden
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      # lease for controller manager
      - dnslb-controller-manager-lease
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: dnslb
  name: dnslb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dnslb
subjects:
  - kind: ServiceAccount
    name: dnslb
    namespace: garden

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: dnslb
  name: dnslb
  namespace: garden
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dnslb
subjects:
  - kind: ServiceAccount
    name: dnslb
    namespace: garden

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dnslb
  name: dnslb-controller-manager
  namespace: garden
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dnslb
        component: dnslb-controller-manager
    spec:
      containers:
        - name: controller-manager
          image: eu.gcr.io/gardener-project/dnslb-controller-manager-local:0.2.0-master
          imagePullPolicy: "Always"
          args:
            - --identity=GardenRing
            - --ttl=60
            - --port=8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            {}

      serviceAccountName: dnslb
      terminationGracePeriodSeconds: 120

