#!/bin/bash
#
# SPDX-FileCopyrightText: 2018 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

case "$1" in 
 lb) watch -d "kubectl -n garden get dnslb -o json | jq '.items[] | (([.metadata.name,\" [\",.spec.DNSName,\"]\"] | join(\"\")), .status)'";;
 ep) watch -d "kubectl -n garden get dnslbep -o json | jq '.items[] | (([.metadata.name,.spec.ipaddress, \"->\", .spec.loadbalancer] | join(\" \")),.status)'";;
 *) echo wrong type;;
esac
