// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSLoadBalancer) DeepCopyInto(out *DNSLoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSLoadBalancer.
func (in *DNSLoadBalancer) DeepCopy() *DNSLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSLoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSLoadBalancerActive) DeepCopyInto(out *DNSLoadBalancerActive) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSLoadBalancerActive.
func (in *DNSLoadBalancerActive) DeepCopy() *DNSLoadBalancerActive {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancerActive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSLoadBalancerEndpoint) DeepCopyInto(out *DNSLoadBalancerEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSLoadBalancerEndpoint.
func (in *DNSLoadBalancerEndpoint) DeepCopy() *DNSLoadBalancerEndpoint {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancerEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSLoadBalancerEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSLoadBalancerEndpointList) DeepCopyInto(out *DNSLoadBalancerEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSLoadBalancerEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSLoadBalancerEndpointList.
func (in *DNSLoadBalancerEndpointList) DeepCopy() *DNSLoadBalancerEndpointList {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancerEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSLoadBalancerEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSLoadBalancerEndpointSpec) DeepCopyInto(out *DNSLoadBalancerEndpointSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSLoadBalancerEndpointSpec.
func (in *DNSLoadBalancerEndpointSpec) DeepCopy() *DNSLoadBalancerEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancerEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSLoadBalancerEndpointStatus) DeepCopyInto(out *DNSLoadBalancerEndpointStatus) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ValidUntil != nil {
		in, out := &in.ValidUntil, &out.ValidUntil
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSLoadBalancerEndpointStatus.
func (in *DNSLoadBalancerEndpointStatus) DeepCopy() *DNSLoadBalancerEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancerEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSLoadBalancerList) DeepCopyInto(out *DNSLoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSLoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSLoadBalancerList.
func (in *DNSLoadBalancerList) DeepCopy() *DNSLoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSLoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSLoadBalancerSpec) DeepCopyInto(out *DNSLoadBalancerSpec) {
	*out = *in
	if in.Singleton != nil {
		in, out := &in.Singleton, &out.Singleton
		*out = new(bool)
		**out = **in
	}
	if in.EndpointValidityInterval != nil {
		in, out := &in.EndpointValidityInterval, &out.EndpointValidityInterval
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSLoadBalancerSpec.
func (in *DNSLoadBalancerSpec) DeepCopy() *DNSLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSLoadBalancerStatus) DeepCopyInto(out *DNSLoadBalancerStatus) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = make([]DNSLoadBalancerActive, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSLoadBalancerStatus.
func (in *DNSLoadBalancerStatus) DeepCopy() *DNSLoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(DNSLoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}
