/*
SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	loadbalancerv1beta1 "github.com/gardener/dnslb-controller-manager/pkg/apis/loadbalancer/v1beta1"
	versioned "github.com/gardener/dnslb-controller-manager/pkg/client/clientset/versioned"
	internalinterfaces "github.com/gardener/dnslb-controller-manager/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/gardener/dnslb-controller-manager/pkg/client/listers/loadbalancer/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DNSLoadBalancerEndpointInformer provides access to a shared informer and lister for
// DNSLoadBalancerEndpoints.
type DNSLoadBalancerEndpointInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.DNSLoadBalancerEndpointLister
}

type dNSLoadBalancerEndpointInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDNSLoadBalancerEndpointInformer constructs a new informer for DNSLoadBalancerEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDNSLoadBalancerEndpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDNSLoadBalancerEndpointInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDNSLoadBalancerEndpointInformer constructs a new informer for DNSLoadBalancerEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDNSLoadBalancerEndpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LoadbalancerV1beta1().DNSLoadBalancerEndpoints(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LoadbalancerV1beta1().DNSLoadBalancerEndpoints(namespace).Watch(options)
			},
		},
		&loadbalancerv1beta1.DNSLoadBalancerEndpoint{},
		resyncPeriod,
		indexers,
	)
}

func (f *dNSLoadBalancerEndpointInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDNSLoadBalancerEndpointInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dNSLoadBalancerEndpointInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&loadbalancerv1beta1.DNSLoadBalancerEndpoint{}, f.defaultInformer)
}

func (f *dNSLoadBalancerEndpointInformer) Lister() v1beta1.DNSLoadBalancerEndpointLister {
	return v1beta1.NewDNSLoadBalancerEndpointLister(f.Informer().GetIndexer())
}
