/*
SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/gardener/dnslb-controller-manager/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DNSLoadBalancers returns a DNSLoadBalancerInformer.
	DNSLoadBalancers() DNSLoadBalancerInformer
	// DNSLoadBalancerEndpoints returns a DNSLoadBalancerEndpointInformer.
	DNSLoadBalancerEndpoints() DNSLoadBalancerEndpointInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DNSLoadBalancers returns a DNSLoadBalancerInformer.
func (v *version) DNSLoadBalancers() DNSLoadBalancerInformer {
	return &dNSLoadBalancerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DNSLoadBalancerEndpoints returns a DNSLoadBalancerEndpointInformer.
func (v *version) DNSLoadBalancerEndpoints() DNSLoadBalancerEndpointInformer {
	return &dNSLoadBalancerEndpointInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
